home>/Users/siyudu
applications>/Users/siyudu/Applications
cloud>/Users/siyudu/Cloud
drive>/Users/siyudu/Drive
desktop>/Users/siyudu/Desktop
documents>/Users/siyudu/Documents
downloads>/Users/siyudu/Downloads
library>/Users/siyudu/Library
movies>/Users/siyudu/Movies
music>/Users/siyudu/Music
pictures>/Users/siyudu/Pictures
program>/Users/siyudu/Program
public>/Users/siyudu/Public
share>/Users/siyudu/Share
sites>/Users/siyudu/Sites
